version: '{branch}.{build}'
image: Visual Studio 2017
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/
build_script:
  - cmd: dotnet build -c Release ./src/
after_build:
  - cmd: dotnet pack -c Release --no-build ./src/ -p:NuspecFile=Redis2Go.nuspec
artifacts:
  - path: '\src\Redis2Go\bin\Release\*.nupkg'
    name: drop
    type: NuGetPackage
clone_depth: 1
test_script:
  - cmd: dotnet test -c Release --no-build ./src/
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: 1zciV0BMoo9LscAiQzNEHKsZ5H5liuN1eSO2Mc3nF9mgcgzRN74pYMkvpu6JyquI

for:

-
  branches:
    only:
      - master
  after_build:
    - cmd: dotnet pack -c Release --no-build ./src/ -p:NuspecFile=Redis2Go.nuspec
  deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: 1zciV0BMoo9LscAiQzNEHKsZ5H5liuN1eSO2Mc3nF9mgcgzRN74pYMkvpu6JyquI
    on:
      branch: master
      appveyor_repo_tag: true