name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/vagyokc4/Redis2Go.Omega/index.json" -UserName ryanhelms &&
           nuget pack  &&
           nuget push "Redis2Go.Omega.0.0.1.nupkg" -Source "GitHub"
    - name: Test
      run: dotnet test --no-restore --verbosity normal
